BEGIN TRANSACTION;

CREATE TABLE type(
    id_type INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name_type VARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE metric(
    id_metric INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    value_metric DOUBLE PRECISION NOT NULL,
    type_metric INT NOT NULL REFERENCES type(id)
);

COMMIT;
