coverage:
  round: down
  range: '55...100'
  status:
    patch:
      default:
        target: 20%
    project:
      default:
        target: auto
        threshold: 0%
  ignore:
    - "pkg/pgcontainer/*"
    - "internal/repo/db/*"
